development:
  adapter: postgresql
  encoding: unicode
  database: ScreenOverflow_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ScreenOverflow_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ScreenOverflow
  pool: 5
