
google_client_id: 387745481483.apps.googleusercontent.com
google_secret: 3KKA-oKzJyf6RLfN_RLyjQJj
google_redirect_uri: http://localhost:3000/auth/google_oauth2/callback


common: &common
  dev_key: AIzaSyBaGT_j_saH5yUoN1VZCh65TnnIOOtCq1U
  username:  screenoverflow
  password:  mvclover
  
test:
  <<: *common
development:
  <<: *common
production:
  <<: *common



