
google_client_id: 387745481483.apps.googleusercontent.com
google_secret: 3KKA-oKzJyf6RLfN_RLyjQJj
google_redirect_uri: http://localhost:3000/auth/google_oauth2/callback
google_dev_key: AIzaSyBaGT_j_saH5yUoN1VZCh65TnnIOOtCq1U
google_username: screenoverflow
google_password: mvclover
